### ISSUE TITLE
Hang on raid load

### ISSUE THREAD

**Issue by Yojenkz** [space-commits/SPT-FOV-Fix#10]
![errorthing](https://github.com/space-commits/SPT-FOV-Fix/assets/71236206/9ebf7e22-75c4-42d3-8b55-aa6499ceba52)

Console Error image attached;

When entering raid, the character is stuck at a stand still and will not pull out the weapon
cannot use tab nor esc
can open console

issue occured when loading with a 2x monstrum optic attached to the arbalet mount on a sniper mosin

EDIT: Could not repro on another weapon (TX15)
tested another optic on the arbalet mount (VuDU in Loabev[Spelling]), issue did not persist
issue persists across 3.0 and 3.1

**Comment by space-commits** [comment]
Can't reproduce. You're using the latest test build on SPT 3.5.8?


![2023-07-13 13-45 _519 9, 9 3, 204 2_0 0, 0 8, 0 0, -0 6_14 00 (0)](https://github.com/space-commits/SPT-FOV-Fix/assets/57108281/570dc1d1-0210-4bf5-b30d-4cf2d9a12657)
![2023-07-13 13-45 _519 9, 9 3, 204 2_0 0, 0 8, 0 0, -0 6_13 99 (0)](https://github.com/space-commits/SPT-FOV-Fix/assets/57108281/ecfe07d5-a6ad-4eb8-92e8-a821062e4c9e)

**Comment by Yojenkz** [comment]
![build](https://github.com/space-commits/SPT-FOV-Fix/assets/71236206/a3108129-be7d-4967-9e89-0c37968039bb)
 Yes, it persists across both the 3.0 and 3.1 releases on 3.5.8 here
 
![mosinb](https://github.com/space-commits/SPT-FOV-Fix/assets/71236206/3edf11d1-5ea8-41db-88d6-ef3d90fa4533)
i am currently attempting to load with an identical mosin build to yours to see if its something else interfering

**Comment by Yojenkz** [comment]
no, same problem

im going to do a reinstall and see if the issue resolves itself.
could be a mod conflict. ill return or close this if I resolve it

**Comment by space-commits** [comment]
![2023-07-13 13-45 _519 9, 9 3, 204 2_0 0, 0 8, 0 0, -0 6_13 99 (0)](https://github.com/space-commits/SPT-FOV-Fix/assets/57108281/a2129159-d4ab-4500-a6c9-c9d7ab5abe51)
![2023-07-13 14-54 _558 4, 3 3, 44 3_0 0, 0 9, 0 0, -0 4_15 27 (0)](https://github.com/space-commits/SPT-FOV-Fix/assets/57108281/2532448e-93e6-4ebf-b535-f57c78f8f210)

**Comment by Yojenkz** [comment]
issue does not persist on a fresh SPT install with only this mod installed
