### ISSUE TITLE
Mod not working as of today

### ISSUE THREAD

**Issue by MAYMAX** [space-commits/SPT-FOV-Fix#26]
didn't change anything, didn't add any (more) mods, restart didn't fix it so didn't reinstalling it, mod shows up in the launcher, no errors directly in the server thingy
never had issues before with ur mod 
Btw idk if it matters but i still had my settings after reinstalling

**Comment by l3kill3rdu59210** [comment]
did you fix the bug i have it too bro

**Comment by MAYMAX** [comment]
So the mod was actually bugged (i tested the tac30, valday and sv98 scope) and after reinstalling and restarting everything a few times it just worked
afer the reinstall i actually thought it was still bugged but that was only because i tested the valday which actually doesnt work in general
And with the help and some research of some people and the spt dc we found out that variable zoom only works for[ LPVO scopes](https://shootingmystery.com/lpvo-meaning/) (tldr battery powered scopes with 1-4 to 1-10x zoom basically thats it) 
So the valday for example isnt one of those so u cant zoom with it
