### ISSUE TITLE
Allow Toggle Zoom While Not Aiming No Longer works unless zoom on Hold breath is Enabled

### ISSUE THREAD

**Issue by Jakerino** [space-commits/SPT-FOV-Fix#28]
Allow Toggle Zoom While Not Aiming no longer works unless zoom on Hold breath is Enabled

It's a solid change - but I liked being able to Arma Zoom without having to hold breath - and then choosing when to hold my breath. 

If fixable - it's appreciated!

**Comment by space-commits** [comment]
you misunderstand how the config work, read the tooltips

**Comment by Jakerino** [comment]
Pre Hold breath, My interpretation of this command and its tool tips - performed exactly as I expected it to - and now it doesn't. This feels slightly gaslighty - as you have replied the same thing to other commenters - AND your fix is to just set the non ADS fov fix to 1.0 - which seems like a bandaid to a check box that now seemingly makes no changes!

Don't get me wrong - I'll do that and go about my merry way - however;
Can you explain to me in more words than the tooltip what this check box does?
