### ISSUE TITLE
[FEATURE] Disable movement speed change (using scroll wheel) while aiming

### ISSUE THREAD

**Issue by maxomatic458** [space-commits/SPT-FOV-Fix#30]
This would make it possible to use the scroll wheel for changing the magnification without having to unbind it from the settings

**Comment by maxomatic458** [comment]
@space-commits why was that closed exactly?
Is that already implemented or planned?

**Comment by space-commits** [comment]
There are dozens of reasons why someone can close an issue, be respectful when it happens
