### ISSUE TITLE
[Feature Request] Arma like ADS and Zoom in

### ISSUE THREAD

**Issue by CapitalGrin** [space-commits/SPT-FOV-Fix#31]
I'm really appreciate for your work, but there's a little idea you may like:

Just like Arma, You can ADS by right cilck and hold right click to zoom in (hold breath) , which means Only after you right click and Aiming down sight, then you can hold right click to Zoom in (hold breath). while canceling the ADS should have a click delay, so that hold right click can not cancel the ADS.
Original EFT's keybind can not do this, Right click and holding right will be triggered at the same time.

Please consider it as a future plan , And thank you again for your Great work.

**Comment by space-commits** [comment]
Not feasible to override EFT keybind behaviour
