### ISSUE TITLE
[Issue] 3.9.0 RC1

### ISSUE THREAD

**Issue by JoelHauser** [space-commits/SPT-FOV-Fix#34]
Performance seems to tank, also "geff false" upon server start up! Much love, amazing mod cant wait for full release <3

**Comment by Max-Pare** [comment]
Yep, this is also the case for me.

**Comment by space-commits** [comment]
Check for updates on discord, resolved in RC2

**Comment by JoelHauser** [comment]
Works wonderfully! youre the goat
